name = "soundcalc"
defaultTargets = ["Soundcalc", "SoundcalcIO"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#v4.30.0"

[[lean_lib]]
name = "Soundcalc"

[[lean_lib]]
name = "SoundcalcIO"

[[lean_exe]]
name = "tomlparser"
root = "SoundcalcIO.TomlParser"