name = "soundcalc"
defaultTargets = ["Soundcalc", "SoundcalcIO", "leanemitter", "mdrenderer"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#v4.30.0"

[[lean_lib]]
name = "Soundcalc"

[[lean_lib]]
name = "SoundcalcIO"

[[lean_exe]]
name = "leanemitter"
root = "SoundcalcIO.LeanEmitter"

[[lean_exe]]
name = "mdrenderer"
root = "SoundcalcIO.MdRenderer"