[zkevm]
name = "OpenVM2"
version = "2.0.0"
field = "BabyBear^4"
hash_size_bits = 256

[swirl]
logup_max_interaction_count = 2013265921
logup_log_max_message_length = 7
logup_pow_bits = 18

[[circuits]]
protocol_family = "SWIRL"
name = "app"
l_skip = 4
n_stack = 20
w_stack = 2048
log_blowup = 1
whir_folding_pow_bits = 5
whir_mu_pow_bits = 15
explicit_regime = "unique"
whir_num_queries = [193, 88, 81, 81]
constraint_degree = 3
max_constraints_per_air = 3183
num_airs = 72
max_log_trace_height = 24
num_trace_columns = 24381
max_interactions_per_air = 976
soundness_max_constraints_per_air = 5000
soundness_num_airs = 100
soundness_max_log_trace_height = 24
soundness_num_trace_columns = 30000
soundness_max_interactions_per_air = 1000
proof_size_num_public_values = 20

[[circuits]]
protocol_family = "SWIRL"
name = "leaf"
l_skip = 4
n_stack = 17
w_stack = 2048
log_blowup = 2
whir_folding_pow_bits = 4
whir_mu_pow_bits = 13
explicit_regime = "unique"
whir_num_queries = [118, 84, 81]
constraint_degree = 4
max_constraints_per_air = 282
num_airs = 42
max_log_trace_height = 21
num_trace_columns = 1679
max_interactions_per_air = 78
soundness_max_constraints_per_air = 1000
soundness_num_airs = 50
soundness_max_log_trace_height = 21
soundness_num_trace_columns = 2000
soundness_max_interactions_per_air = 100
proof_size_num_public_values = 121

[[circuits]]
protocol_family = "SWIRL"
name = "internal_for_leaf"
l_skip = 2
n_stack = 17
w_stack = 512
log_blowup = 3
whir_folding_pow_bits = 18
whir_mu_pow_bits = 20
explicit_regime = "list"
explicit_m = 2
whir_num_queries = [68, 30, 20]
logup_pow_bits = 19
constraint_degree = 4
max_constraints_per_air = 282
num_airs = 42
max_log_trace_height = 19
num_trace_columns = 1663
max_interactions_per_air = 78
soundness_max_constraints_per_air = 1000
soundness_num_airs = 50
soundness_max_log_trace_height = 19
soundness_num_trace_columns = 2000
soundness_max_interactions_per_air = 100
proof_size_num_public_values = 121

[[circuits]]
protocol_family = "SWIRL"
name = "internal_recursive"
l_skip = 2
n_stack = 17
w_stack = 512
log_blowup = 3
whir_folding_pow_bits = 18
whir_mu_pow_bits = 20
explicit_regime = "list"
explicit_m = 2
whir_num_queries = [68, 30, 20]
logup_pow_bits = 19
constraint_degree = 4
max_constraints_per_air = 282
num_airs = 42
max_log_trace_height = 19
num_trace_columns = 1663
max_interactions_per_air = 78
soundness_max_constraints_per_air = 1000
soundness_num_airs = 50
soundness_max_log_trace_height = 19
soundness_num_trace_columns = 2000
soundness_max_interactions_per_air = 100
proof_size_num_public_values = 121

[[circuits]]
protocol_family = "SWIRL"
name = "hook"
l_skip = 2
n_stack = 18
w_stack = 80
log_blowup = 2
whir_folding_pow_bits = 12
whir_mu_pow_bits = 11
explicit_regime = "list"
explicit_m = 1
whir_num_queries = [193, 42, 24]
constraint_degree = 4
max_constraints_per_air = 1000
num_airs = 50
max_log_trace_height = 20
num_trace_columns = 2000
max_interactions_per_air = 100
proof_size_num_public_values = 18

# the root aggregation layer is only used for STARK-to-SNARK recursion
[[circuits]]
protocol_family = "SWIRL"
name = "root"
l_skip = 2
n_stack = 18
w_stack = 18
log_blowup = 4
whir_folding_pow_bits = 20
whir_mu_pow_bits = 20
explicit_regime = "list"
explicit_m = 1
whir_num_queries = [57, 28, 19]
constraint_degree = 4
max_constraints_per_air = 1000
num_airs = 50
max_log_trace_height = 21
num_trace_columns = 2000
max_interactions_per_air = 100
proof_size_num_public_values = 16
