[zkevm]
name = "OpenVM"
version = "1.5.0"
field = "BabyBear^4"
hash_size_bits = 256

# The OpenVM aggregation topology is described in <https://docs.openvm.dev/specs/architecture/continuations>
# Circuits are classified as App, Leaf, Internal.{i} for different aggregation layers.
# The App circuit dimensions vary at runtime based on which chips are active in a given continuation segment and the exact instructions in a segment.
# The Leaf and Internal aggregation circuit dimensions vary based on the dimensions of the child circuits it is aggregating.
# Below we provide parameters based on a near-worst case analysis of the circuits.


# The circuit data below were extracted using this procedure:
#  https://github.com/ethereum/soundcalc/pull/74#issuecomment-4032053280
#

[[circuits]]
protocol_family = "FRI_STARK"
name = "app"
# blowup_factor = 2
rho = 0.5
trace_length = 8388608 # 1 << 23
air_max_degree = 3
# Total number of constraints across all AIRs used in a proof.
# DEEP-ALI does algebraic batching of constraints _per AIR_. Here we conservatively take a union bound and report as if batching across all AIRs.
num_constraints = 15000
# The proof system uses multi-FRI, which batches together polynomials of different heights. Since the `batch_size` parameter is used to calculate the batch-FRI soundness, we report here the maximum, over distinct trace heights, of the number of base field polynomials of that height that are algebraically batched. This corresponds to the highest count of algebraic batching that is done in multi-FRI within a single proof.
# A trace polynomial over the base field opened at 2 points gets a contribution of 2. A trace polynomial over the extension field opened at 2 points gets a contribution of 8.
# Note that since this number varies based on the exact configuration of trace dimensions, the reported number is based on a statistical sampling.
batch_size = 80000
# All trace polynomials are opened only at local, next (rotation) points. Quotient polynomials are only opened at one point.
opening_points = 2
power_batching = true
# https://github.com/openvm-org/stark-backend/blob/0c33328916d95047325b60a8044ecf9468db84bb/crates/stark-sdk/src/config/fri_params.rs#L183
num_queries = 193
fri_folding_factors = [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
fri_early_stop_degree = 2 # =blowup_factor
grinding_batching_phase = 20
grinding_query_phase = 20
grinding_deep = 5

[[circuits]]
protocol_family = "FRI_STARK"
name = "leaf"
# blowup_factor = 2
rho = 0.5
trace_length = 8388608 # 1 << 23
air_max_degree = 3
num_constraints = 15000
batch_size = 80000
opening_points = 2
power_batching = true
# https://github.com/openvm-org/stark-backend/blob/972f5dbecb6ab3ff7e3e978e9087235ad17c1de9/crates/stark-sdk/src/config/fri_params.rs#L65
num_queries = 193
fri_folding_factors = [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
fri_early_stop_degree = 2 # = blowup_factor
grinding_batching_phase = 20
grinding_query_phase = 20
grinding_deep = 5

[[circuits]]
protocol_family = "FRI_STARK"
name = "internal"
# blowup_factor = 4
rho = 0.25
trace_length = 2097152 # 1 << 21
air_max_degree = 4
num_constraints = 15000
batch_size = 4000
opening_points = 2
power_batching = true
# https://github.com/openvm-org/stark-backend/blob/972f5dbecb6ab3ff7e3e978e9087235ad17c1de9/crates/stark-sdk/src/config/fri_params.rs#L71
num_queries = 118
fri_folding_factors = [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
fri_early_stop_degree = 4 # = blowup_factor
grinding_batching_phase = 16
grinding_query_phase = 20
grinding_deep = 5

[[circuits.lookups]]
name = "lookup"
logup_type = "univariate"
rows_L = 128  # 2^7
rows_T = 0  # one table
num_columns_S = 1
grinding_bits_lookup = 18
